<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option - Perfil Track de Carga Expo</name>
   <tag></tag>
   <elementGuidId>08ef5410-323f-488d-8ed6-578982d6f2de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[(text() = 'Track de Carga Expo' or . = 'Track de Carga Expo')])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-16-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46feb7df-8748-4bb4-a01f-3023e66b31f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-d7l1ni-option</value>
      <webElementGuid>eed8aea9-a298-426a-955f-10354b12c9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47b834ad-2d21-4657-9ca6-e5823e008511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-16-option-0</value>
      <webElementGuid>5245a100-347d-439f-866b-f92e399795ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>afe55584-8c12-4a6f-90ca-b0cedbf54e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Track de Carga Expo</value>
      <webElementGuid>c093f6fe-bb1a-4016-8c37-8efdd64f5401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-16-option-0&quot;)</value>
      <webElementGuid>77116def-09e7-434d-ac8a-8852a98fd133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-16-option-0']</value>
      <webElementGuid>d5bab15f-a564-401c-9609-eac3408779b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-16-listbox']/div/div</value>
      <webElementGuid>71ddb4bf-7357-45dd-9a8d-5449e57c4a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrador'])[17]/following::div[8]</value>
      <webElementGuid>b07a7fe7-3ccc-4e56-8208-6436245e2dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='option Administrador, selected.'])[1]/following::div[12]</value>
      <webElementGuid>a382be41-f791-4dda-90cc-f05718cfceb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código aerolínea:'])[1]/preceding::div[2]</value>
      <webElementGuid>69bf3a5c-d8ac-45c2-bc6c-d225fe3c9626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::div[3]</value>
      <webElementGuid>e74ecaa0-703d-4639-9c45-aa2746a52039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div</value>
      <webElementGuid>23b83ae2-c07d-497c-a4dd-3ddd1dba343f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-16-option-0' and (text() = 'Track de Carga Expo' or . = 'Track de Carga Expo')]</value>
      <webElementGuid>07e29af6-2e51-47a0-b2dc-54ece5628463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
