<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option - Rol Agente de carga</name>
   <tag></tag>
   <elementGuidId>2f73d01a-7d51-426d-a857-dbef0c54cf03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-7-option-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Agente de carga' or . = 'Agente de carga')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f404a546-de67-4288-bf5f-c64fe7d64a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-d7l1ni-option</value>
      <webElementGuid>bf0527e7-cadc-40fd-aed1-1067fa7688f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b260917-15eb-42c8-b21a-1880a68f5a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-7-option-3</value>
      <webElementGuid>5280506a-22c7-4b37-9234-6275b6182275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4001ce77-ef4e-4c4d-be1c-8ba7009e5f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agente de carga</value>
      <webElementGuid>fb2509f1-74d9-46f5-ab55-0b6f87ac9952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-7-option-3&quot;)</value>
      <webElementGuid>a9a01874-3000-416d-8f35-fdb226f4f695</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-option-3']</value>
      <webElementGuid>dbd6ef6b-ec07-47ed-ac3e-9aeff6b3c71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-listbox']/div/div[4]</value>
      <webElementGuid>a7378709-fff2-435e-9e82-36c3fac1aabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GHA'])[2]/following::div[1]</value>
      <webElementGuid>68b67be1-5a75-4a08-8d1f-de72bb08c774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agente de Aduana'])[1]/following::div[2]</value>
      <webElementGuid>e49f9d35-9c13-480d-9343-74faec4046e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aerolinea'])[1]/preceding::div[1]</value>
      <webElementGuid>a355a893-f2a1-46dd-af3c-de123f6ed323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil:'])[2]/preceding::div[2]</value>
      <webElementGuid>35efd6e4-ca15-4242-a6d9-aed42b31e808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agente de carga']/parent::*</value>
      <webElementGuid>5a0ac196-26b0-4098-9a5e-aed3ac6622d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>7ea934bf-0b92-4361-8a4a-f90ca9184a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-7-option-3' and (text() = 'Agente de carga' or . = 'Agente de carga')]</value>
      <webElementGuid>0682bdf5-d871-42a2-9c31-1a43b8a87a45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
