<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option - Rol Aerolinea</name>
   <tag></tag>
   <elementGuidId>f36cc891-24ba-4a87-91f8-a73d8ab94d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[(text() = 'Aerolínea' or . = 'Aerolínea')])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-7-option-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9e157ae-be00-4230-b33d-5b4dc6042e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-d7l1ni-option</value>
      <webElementGuid>a70dbfd7-05ac-4c5d-ab72-7b9647a9cd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95a1df4c-1352-4cca-8539-7190c34bc26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-7-option-4</value>
      <webElementGuid>bd0c6883-ddeb-41ef-8b32-6271ea051353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6378ad6c-d090-4268-8f08-75bacc06e3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aerolinea</value>
      <webElementGuid>aec4c141-8566-4762-a0ee-d54e59c50613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-7-option-4&quot;)</value>
      <webElementGuid>26fbdda8-e540-4a5a-8ecf-361f106e021b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-option-4']</value>
      <webElementGuid>005c7bf8-7c99-4e31-a9d9-57de82fe7bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-listbox']/div/div[5]</value>
      <webElementGuid>9c56d4f1-b7bd-4cf9-afc7-a7a2ad1a9198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agente de carga'])[2]/following::div[1]</value>
      <webElementGuid>eaf5e2d2-9a7a-45ed-9d7c-5f953ffc1135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GHA'])[1]/following::div[2]</value>
      <webElementGuid>0329e2ac-a504-4642-955e-1a06799892c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil:'])[2]/preceding::div[1]</value>
      <webElementGuid>f4e43db8-3276-43ce-9bfb-da41903c4a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione una opción'])[4]/preceding::div[1]</value>
      <webElementGuid>464aab41-f8c7-4814-a396-a849f594bb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aerolinea']/parent::*</value>
      <webElementGuid>96dd67fa-5fda-4a0e-ae49-1b66eb2d5273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]</value>
      <webElementGuid>5054f4d0-9161-4c6f-88d7-b6e71c4e6696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-7-option-4' and (text() = 'Aerolinea' or . = 'Aerolinea')]</value>
      <webElementGuid>7a5afc98-ab16-4be4-91e8-4783c19ccb2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
