<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option - Código Aerolínea XTL</name>
   <tag></tag>
   <elementGuidId>fc443a5f-4478-4a7e-b046-eb4e04ad4157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id=':rj:-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>15cc8583-c5ae-4638-b3a1-38f54c968ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option MuiBox-root css-0 Mui-focused</value>
      <webElementGuid>3ef08b0a-797e-49e8-9357-e832b2ca3bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>68fcce4d-4ae5-496b-8c40-895afde3be44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>44c6a12e-a5f7-4f0d-adf3-2398b6046008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rj:-option-0</value>
      <webElementGuid>45269a9e-fe5e-4f0b-ad01-2b45ae04e3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>990045d1-954a-4d2b-92ea-2478bae668fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9651be4a-96d9-4273-983f-15108fc4861a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>accc5061-ba0b-4806-8c52-f6aba4eb596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XTL - TALMA SERVICIOS AEROPORTUARIOS S.A - 20204621242</value>
      <webElementGuid>5815df62-e55d-43b3-841e-0a7813f84900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rj:-option-0&quot;)</value>
      <webElementGuid>5a5bbf61-ffec-4c0c-8e0c-4aa4dc7a32c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id=':rj:-option-0']</value>
      <webElementGuid>cd68b1e5-8f18-4b62-8f1f-5d24bd715e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':rj:-listbox']/li</value>
      <webElementGuid>544e41c0-049d-4322-a024-8133620ce6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar usuario'])[1]/following::li[1]</value>
      <webElementGuid>5a18f401-8216-4b1d-a17e-aa5e2548d69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione una opción'])[4]/following::li[1]</value>
      <webElementGuid>2e997326-ac46-40fb-9b22-33b861c2d666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='XTL']/parent::*</value>
      <webElementGuid>8795286b-961b-46f5-ae84-73f8e63d1c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/ul/li</value>
      <webElementGuid>6575952a-3257-40dc-9e64-373c7bf17579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = ':rj:-option-0' and (text() = 'XTL - TALMA SERVICIOS AEROPORTUARIOS S.A - 20204621242' or . = 'XTL - TALMA SERVICIOS AEROPORTUARIOS S.A - 20204621242')]</value>
      <webElementGuid>1b165132-ce28-481b-9d3d-efed8618980f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
