<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>02. H2 - Password Updates and Deep Links</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>kimberly.mccubbinalva@gmail.com;kmccubbin@progrez.pe;</mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>31ab6e0b-0981-446e-8219-f1376f0c7bb7</testSuiteGuid>
   <testCaseLink>
      <guid>d0e35876-2ec7-46f6-9fec-4af6eb55272b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_000 - Navigate AerolineaAdminTrackCarga Modules</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f9b4565c-370e-41f5-99b3-55f511ebf5d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_000 - Navigate AerolineaTrackCarga Modules</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c17486d2-1735-41a1-ab8b-dd0b62090042</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_000 - Navigate AgenteAdminTrackCarga Modules</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0f42a492-af81-45b4-93a6-d12cf1b50fd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_000 - Navigate GHAAdminTrackCarga Modules</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d7650e93-3d8f-46f2-a9df-b36de8f22423</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_006 - Login BackOfficeAdmin Pass</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e2bfa78c-5788-494c-9c9f-25acccd5cd1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_007 - Login BackOfficeAdmin Fails Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ef250d4-80ee-4b0f-a4f4-52ddbce75c1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bedb68dd-3940-4e07-893e-cc5d22c88cc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2b623ee-7447-46de-99f6-d9364735e708</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/Deleted flow/CP_008 - Login BackOffice Fails Deleted</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2a66458f-3e15-46be-b3ad-beb932918f2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_009 - Login BackOfficeAdmin Fails Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>94d4ab63-47a5-4fcb-ba1d-e07b125717f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_010 - Navigate BackOfficeAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0411ec78-87d5-440c-9c9c-d533db422f0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_011 - Login BackOfficeTrackCarga Pass</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6cfcb233-6c4e-443f-981a-c61c561234f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_012 - Login AerolineaAdmin Pass</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>408fe304-4dcf-48eb-9f24-6f93ebc87f7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_013 - LoginAerolineaAdmin Fails Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9723b2b7-8501-4450-a452-4c97e31b18a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/Deleted flow/CP_014 - AerolineaAdmin Fails Deleted</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>54dda2ac-00eb-40dd-afe9-03ac42e9521a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_015 - Login AerolineaAdmin Fails Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c775db4f-c2da-45b1-8c32-387f54eb38aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_016 - Navigate AerolineaAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>29e6972c-380d-4b48-a6ec-789f968ff3fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_017 - Login AerolineaTrackCarga Pass</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2ffe5039-8693-4111-b754-c56fd881ecec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_018 - Login GHAAdmin Pass</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a6c14b2c-f018-4ac3-91c5-f30a9515713c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_019 - Login GHAAdmin Fails Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0fca80f2-c824-4443-8802-6a51ab1adc40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/Deleted flow/CP_020 - Login GHAAdmin Fails Deleted</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b25bf49c-bfa2-4cde-ab8f-2a8ef69cf6f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_021 - Login GHAAdmin Fails Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b5065d91-8371-4d30-b6e8-bd54fe398392</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_022 - Navigate GHAAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>60402147-430e-49f3-bf30-681843176581</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_023 - Navigate GHATrackCarga</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>50a49b6b-bb6c-4f59-a81c-23137a81e9c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_024 - Login AgenteAdmin Pass</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5a8791b3-a710-4c85-823e-96ec251d9276</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_025 - Login AgenteAdmin Fails Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2c0ee672-e5d3-4e70-b1ad-0dcff0a130c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/Deleted flow/CP_026 - Login AgenteAdmin Fails Deleted</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ccad4f62-1bed-41cb-ac80-5874d3b7f2dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_027 - Login AgenteAdmin Fails Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>68cd917a-dd0b-4433-9b5a-7af95ac70ef0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_028 - Navigate AgenteAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6b346d9e-04b4-47ee-8aa0-c98fa70b808c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_029 - Navigate AgenteTrackCarga</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>10d2422b-67ca-479b-ac1f-258300a78cbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_01 - System Access/CP_154 - Logout All Users</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5d187536-02d4-49ec-8839-9149a4d22482</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_15 - Deep Link Access/CP_152 - DeepLink Users Module</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e3712c9f-39ea-4a92-951a-76a775f419b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.1 - CU_15 - Deep Link Access/CP_153 - DeepLink Exportation Module</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ada6834b-0133-4e4d-a7d1-d3b350de2952</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.2 - CU_02 - Password Update/CP_030 - Update Password All Users</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>800dd34c-b360-49b3-8df8-455d695dcf85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030c85b0-f7c8-4790-84c9-0685117c73d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b435a89a-1223-4baa-bcb7-a35ff9c5027c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a033335-0b69-4302-a8ae-817b40046d55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a81c09f-b662-446a-8ff9-56661ff3ae08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>475b0dcf-9006-4918-9c45-4c5c59d6efbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.2 - CU_02 - Password Update/CP_031 - Verification Code Expires</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>800dd34c-b360-49b3-8df8-455d695dcf85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030c85b0-f7c8-4790-84c9-0685117c73d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b435a89a-1223-4baa-bcb7-a35ff9c5027c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a033335-0b69-4302-a8ae-817b40046d55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a81c09f-b662-446a-8ff9-56661ff3ae08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bb39bd6-62ec-47a2-a6e1-543ff5b21029</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.2 - CU_02 - Password Update/CP_032 - Resend Verification Code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>800dd34c-b360-49b3-8df8-455d695dcf85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030c85b0-f7c8-4790-84c9-0685117c73d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b435a89a-1223-4baa-bcb7-a35ff9c5027c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a033335-0b69-4302-a8ae-817b40046d55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a81c09f-b662-446a-8ff9-56661ff3ae08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2d49132-dc88-496d-8901-474b4d9ed577</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.2 - CU_02 - Password Update/CP_033 - Resent Verification Code And Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>800dd34c-b360-49b3-8df8-455d695dcf85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030c85b0-f7c8-4790-84c9-0685117c73d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b435a89a-1223-4baa-bcb7-a35ff9c5027c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a033335-0b69-4302-a8ae-817b40046d55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a81c09f-b662-446a-8ff9-56661ff3ae08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39bce559-6414-450c-83df-9e923b3944d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.2 - CU_02 - Password Update/CP_034 - Update Password Fails Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e070cdf8-3724-4606-80ca-f25bc1b1c39f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/H02.2 - CU_02 - Password Update/CP_035 - Update Password Fails Email Format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
